language: php

sudo: false

php:
  - 7.1

env:
  global:
    - DEFAULT=0

matrix:
  include:
    - php: 7.3
      env: CHECKS=1 DEFAULT=0

    - php: 7.1
      env: PHPCS=1 DEFAULT=0 PREFER_LOWEST=1

  fast_finish: true

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer require --dev dereuromark/composer-prefer-lowest; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest; fi

  - if [[ $PHPCS == 1 ]]; then composer cs-check; fi

  - if [[ $CHECKS == 1 ]]; then composer cs-check; fi
  - if [[ $CHECKS == 1 ]]; then composer phpstan; fi

notifications:
  email: false
