language: php

php:
  - 7.1
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: CHECKS=1 DEFAULT=0

    - php: 7.1
      env: DEFAULT=0 PREFER_LOWEST=1

  fast_finish: true

before_install:
  - if [[ ${TRAVIS_PHP_VERSION} != "7.4" ]]; then phpenv config-rm xdebug.ini ; fi

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer require --dev dereuromark/composer-prefer-lowest; fi

script:
  - if [[ $DEFAULT == 1 ]]; then composer phpstan; fi

  - if [[ $PREFER_LOWEST == 1 ]]; then composer cs-check; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest; fi

  - if [[ $CHECKS == 1 ]]; then composer cs-check; fi

cache:
    directories:
        - $HOME/.composer/cache

notifications:
  email: false
